# Default values for the WordPress Helm chart

replicaCount: 1

# WordPress Image Settings
image:
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# ServiceAccount settings
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Pod security context
podSecurityContext: {}
  # fsGroup: 2000

# Container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Service Settings
service:
  type: ClusterIP
  port: 80

# Ingress Settings
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: wordpress-demo.jadomars.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: wordpress-demo-tls
      hosts:
        - wordpress-demo.jadomars.com

# WordPress Database settings (MySQL integration)
mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  auth:
    rootPassword: root_password  # Set MySQL root password
    username: wordpress_user      # Set MySQL user for WordPress
    password: wordpress_password  # Set MySQL user password for WordPress
    database: wordpress_db        # Set the database name for WordPress
  primary:
    service:
      port: 3306
  persistence:
    enabled: true
    size: 10Gi                # Size of the volume
    storageClass: "gp2"       # StorageClass; adjust as necessary

resources:
  # Optional resource limits and requests
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Volumes and Mounts
volumes: []
# volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
